coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    ignore:
      - "src/examples"  # coverage doesn't come from examples
